### ISSUE TITLE
Maldita Castilla controls don't work (RG351V AmberELEC) 

### ISSUE THREAD

**Issue by tabreturn** [PortsMaster/PortMaster-Releases#5]
Maldita Castilla runs fine, but there's no controller input. 

System info
RG351V running latest stable AmberELEC (20200627)
PortMaster v6.59

(Otherwise, loving PortMaster -- great work!)

**Comment by Cebion** [comment]
Fixed in pre-release. Will be available in next release.

**Comment by tabreturn** [comment]
Any updates on this? Can you confirm this is fixed in the latest release? Will I need to reinstall PrtMaster on my RG351V? Thanks

**Comment by Cebion** [comment]
> Any updates on this? Can you confirm this is fixed in the latest release? Will I need to reinstall PrtMaster on my RG351V? Thanks

Replace this gptokeyb version in your portmaster folder.
https://github.com/kloptops/gptokeyb/releases/tag/v0.1.2

Fix will also be released into portmaster.

**Comment by tabreturn** [comment]
I can confirm that your fix works for me, @Cebion. Thanks :)
